---
abstract: 'import Python-style constructor functions'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Constructor-Pythonic
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Acme::Constructor::Pythonic:
    file: lib/Acme/Constructor/Pythonic.pm
    version: 0.002
requires:
  Exporter::Tiny: 0
  Module::Runtime: 0
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Acme-Constructor-Pythonic/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Acme-Constructor-Pythonic
  homepage: https://metacpan.org/release/Acme-Constructor-Pythonic
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-acme-constructor-pythonic.git
version: 0.002
