---
abstract: 'import Python-style constructor functions'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Acme::Constructor::Pythonic
name: Acme-Constructor-Pythonic
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::OptList: 0
  Module::Runtime: 0
  Sub::Install: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Acme-Constructor-Pythonic
  homepage: https://metacpan.org/release/Acme-Constructor-Pythonic
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-acme-constructor-pythonic
version: 0.001
